

name: Liquibase Migration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # workflow_dispatch:

jobs:
  liquibase-update:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Format SQL files with PowerShell
        run: |
          pwsh ./script/format_liquibase_sql.ps1
        shell: pwsh

      - name: Commit and push formatted SQL files
        run: |
          git config user.name "naila-alissa"
          git config user.email "naila.alissa1@inter.ikea.com"
          git add .
          git commit -m "chore: auto-format SQL files with Liquibase headers" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Liquibase
        run: |
          curl -L -o liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.32.0/liquibase-4.32.0.zip
          powershell -Command "Expand-Archive -Path liquibase.zip -DestinationPath liquibase"
          echo "$env:GITHUB_WORKSPACE\\liquibase" | Out-File -Append $env:GITHUB_PATH
        shell: pwsh

      - name: Download JDBC Driver
        run: |
          curl -L -o mssql-jdbc.jar https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.2.0.jre8/mssql-jdbc-12.2.0.jre8.jar

   

      - name: Run Liquibase Update
        env:
          LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
          LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
          LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
        run: |
          liquibase update
        shell: pwsh
